### ISSUE TITLE
IMPROTANT >Textes trops fins  Passer les textes fins en bold pour voir ?

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#11]

**Comment by thibaultvanc** [comment]
la proprieté CSS font-weight n'est pas reconnue par DOMPDF. j'ai passé tous les gris en noir. Cela me parait bien visible. Dans l'attente de votre retour

**Comment by Playologie** [comment]
Quelques améliorations :
- augmenter la taille typo des lignes du header
- dans commande, les références taille sont encore en gris, et trop petit

**Comment by thibaultvanc** [comment]
Quelques améliorations :

- augmenter la taille typo des lignes du header **fait** (passé de 0.8em  à 1em) pour tous les dicuments
- commande, les références taille sont encore en gris, et trop petit **fait**

**Comment by thibaultvanc** [comment]
en ligne
