### ISSUE TITLE
Contenu trop près du bord > A l'impression le contenu trop près du bord est coupé, laisser toujours 0,5 cm sur les 4 cotés

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#12]

**Comment by thibaultvanc** [comment]
ce ci est corrigé si on parle de la meme chose

**Comment by Playologie** [comment]
pas certain qu'on parle e la meme chose, je parle des marges sur les 4 cotés, là c'est 30 pixels, ça me parait un peu juste, il faudrait l'équivalent de 90 mm / 1 cm, beaucoup d'imprimantes ont du mal à imprimer en dessous 
![capture d ecran 2017-02-10 a 12 54 37](https://cloud.githubusercontent.com/assets/24650759/22825945/1c2d75c4-ef90-11e6-9e18-9be6196e895a.png)
