### ISSUE TITLE
"PDF de commande, il manque les miniatures des couleurs / imprimés apès le nom de l'imprimé http://hpics.li/f5c29a3"

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#15]

**Comment by thibaultvanc** [comment]
FAIT - en ligne

**Comment by Playologie** [comment]
Bizarrement, pour cette commande en cours il y a des miniatures encore pas carrées. 
http://playologie.organit.fr/brand-order/#/order/8 
http://playologie.organit.fr/export/order/649751ad30ca6c92a02f6c700989f6ea.pdf

**Comment by thibaultvanc** [comment]
fait -en ligne

**Comment by Playologie** [comment]
pour moi ça affiche toujours des cases non carrées (voir page 2)
http://playologie.organit.fr/export/order/027cf7962dd69ff235bad2e69498c40f.pdf

**Comment by thibaultvanc** [comment]
c'est parceque ce n'était pas en ligne
vous pouvez réessayer
