### ISSUE TITLE
IMPORTANT > Article sans couleur/imprimé

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#16]
"un article peut ne pas avoir de couleur/imprimé : dans ce cas vous n’avez pas affiché les quantités  commandées dans le pdf, elles sont restées à 0 
Exemple marque kfb@playologie.com / mdr : kid2017
Commande n° ORDER-1002"

**Comment by thibaultvanc** [comment]
fait

**Comment by Playologie** [comment]
ok sur organit.fr
