### ISSUE TITLE
En-tête : "Clé n° de compte" (valable dans tous les documents)

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#19]
La clé qui affiche "N° de compte" n'est pas pertinente, à remplacer par "E-mail"
Exemple : 
56 rue du Faubourg Saint Antoine - 75012 Paris - France 
Téléphone : +33 627440709 - N° de compte : db@playologie.com - http://www.designbrand.com

**Comment by thibaultvanc** [comment]
voici la ligne de code : 
@lang('playologie.brand.account.field.phone') : {{$phone->indicative}} {{$phone->number}} - @lang('playologie.brand.customer.edit.main.account_number') : {{$user->email}} - {{$universe->url_website}}<br>

du coups c'est déjà l'email ..

**Comment by Playologie** [comment]
Concerne tous les documents : 
c'est le titre devant l'adresse email qui ne convient pas, ne pas prendre la clé playologie.brand.customer.edit.main.account_number 
mais la clé :
playologie.brand.customer.add.field.email

**Comment by thibaultvanc** [comment]
FAIT- en ligne
