### ISSUE TITLE
En-tête (valable dans tous les documents) > 

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#20]
"Elargir la zone affectée a l'en-tête pour au moins aligner N° de commande et Date 
Voir : http://hpics.li/a467296
et http://hpics.li/f5d5743"

**Comment by Playologie** [comment]
OK pour facture, mais à faire dans BL, PDF de commande (et les documents à venir)

**Comment by thibaultvanc** [comment]
FAIT pour invoice - order - BL
Ce sera pris en compte pour les prochain documents
