### ISSUE TITLE
bas de commande > accompte

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#21]
"Le champ ""deposit required"" doit s'afficher lorsqu'il y a une demande d'acompte 
Pas dans ""conditions de paiement, mais dans la partie à droite :

Sous la barre grise 
Total TTC : XXX EUR
Acompte : XXX EUR (somme demandée ou somme équivalente au % indiqué) - je vous explique si c'est pas clair
Montant restant dû : XXX EUR"

**Comment by thibaultvanc** [comment]
j'ai besoin qu'on en parle

**Comment by Playologie** [comment]
facture avec acompte : http://playologie.organit.fr/brand-invoice/#/invoice/5

**Comment by thibaultvanc** [comment]
fait sur acompte - en ligne sur organit
