### ISSUE TITLE
IMPORTANT > Manque une colonne : prix unitaire > 

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#23]
"Manque une colonne : prix unitaire
Voir gabarit de départ vs le PDF actuel : http://hpics.li/3f9c81b"

**Comment by thibaultvanc** [comment]
fait

**Comment by Playologie** [comment]
cela a créé un décalage, cf ticket https://github.com/thibaultvanc/playologie_exports/issues/29

**Comment by Playologie** [comment]
Je ne vois pas cette ligne dans les factures pour le moment. J'imagine une ligne entre les tailles et les quantités commandées (proche du principe du tableau dans pdf commande)
![capture d ecran 2017-02-06 a 16 13 56](https://cloud.githubusercontent.com/assets/24650759/22652619/690ddb1a-ec87-11e6-9aad-8bd2f39bb9df.png)
 , voir PJ

**Comment by thibaultvanc** [comment]
FAIT
