### ISSUE TITLE
IMPORTANT > Calcul TVA et Port

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#24]
db@playologie.com / design2017

Commande en cours : http://playologie.com/brand-order/#/order/3412
Actuellement le montant du port s'affiche entre parenthèses avec un %
[moon monsters.pdf](https://github.com/thibaultvanc/playologie_exports/files/744487/moon.monsters.pdf)
 voir PJ

Base HT 8,625.00 
TVA 20% = 1 725,00

port HT : 100 EUROS
TVA de port : 20% 

Total TTC port inclus : 10 470,00

Or, le PDF indique : 
Base HT 810,470.00
TVA 20% = 1,725.00 

port HT : 100 EUROS
La ligne de TVA de port n'apparait pas 

Total TTC port inclus : 12,315.00 (tva, port et TVA de port comptés deux fois)

**Comment by Playologie** [comment]
PDF commande + Facture (+ pro forma à venir)

- retirer les parenthèses et le taux entre parenthèses après Shipping
- ajouter dessous une ligne "TVA du transport" (Shipping VAT)
clé = main.order.main.vat_transport
- mettre la parenthèse et le taux de TVA après "TVA du transport". La somme correspondante se place en face.

Voir PJ
![capture d ecran 2017-02-03 a 10 31 19](https://cloud.githubusercontent.com/assets/24650759/22586267/0a4f1644-e9fc-11e6-994c-1108a3fc156c.png)

**Comment by thibaultvanc** [comment]
INVOICE : FAIT -> si c'est ok, je reproduis sur order

**Comment by Playologie** [comment]
aucun changement vu dans commande, ni facture
[6ca53b292a2f3717c02dac12f3fccf19.pdf](https://github.com/thibaultvanc/playologie_exports/files/754454/6ca53b292a2f3717c02dac12f3fccf19.pdf)

**Comment by thibaultvanc** [comment]
en ligne

**Comment by Playologie** [comment]
OK dans Invoice, merci de la reproduire dans commande, et dans pro forma à venir.
Dans les facture d'export le cout du transport d'apparaitra pas (ni le port ni sa TVA donc)
