### ISSUE TITLE
Champ "description" : il correspond au champ "invoice_description" de la table PLAY_brand_collection_product et non "description" tout court

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#26]

**Comment by thibaultvanc** [comment]
Vous avez mis le label 'tous les documents'. le champs est **invoice_description** => c'est pour invoice seulement?
par ailleurs, pouvez vous me faire une capture écran si possible

**Comment by Playologie** [comment]
Je vais simplifier les choses : le produit "Chemise 1"
http://playologie.organit.fr/brand-collection-product/#/5
a une description spéciale pour les douanes qui est la suivante : "shirt customs description"

Si dans brand_doc ils ont coché de montrer la description saisie dans ce champ. 
Prendre ce champ dans tous les documents (et non le descriptif complet du produit, je changerais le terme pour que l'utilisateur sache où sera prise l'info)

**Comment by thibaultvanc** [comment]
FAIT pour les trois documents - pas encore en ligne

**Comment by thibaultvanc** [comment]
en ligne
