### ISSUE TITLE
Adresses de livraison erronnées

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#27]
Marque Racines du Ciel
L'adresse de livraison est erronnée pour de nombreuses commandes migrées et appelle toutes la même adresse (du buyer ID n°1 de la bdd)

_**Je pense que c'est parce que vous n'avez pas copié l'adresse de livraison depuis l'adresse de facturation quand le champ delivery_same_as_billing = 1**_  Du coup ça affiche les coordonnées du buyer n°1 de notre bdd. S'il est possible de les identifier et que je doive juste mettre 1 au lieu de 0 quelque part dans la nouvelle bdd ok, mais il me faut les identifier

Exemple : Les Racines du Ciel
nathalie.goyette@les-racines-du-ciel.com / crisnat

http://playologie.com/brand-order/#/order/2805
Commande n° 100-002-805
Commande de : Argo Mode+Mensch

ADRESSE DE LIVRAISON
default
Kolonienstraat, 11
1000
Brussels, Belgique

Kidzarella SPRL
helen@kidzarella.com
+32 32487119771 (Mobile)

Ancienne BDD :
ID order 2805
ID buyer 11155
ID address : 32296 (qu'on trouve dans table coordinates )

Le mieux est de se refaire expliquer le fonctionnement exact par Ludovic, mais d'apres ce que j'ai compris, il faut donc dupliquer l'adresse de facturation de id_adress en créant une nouvelle entrée et l'associer à l'acheteur dans id_buyeraddress

**Comment by mikael-desharnais** [comment]
Executer ce code SQL corrige la base de donnée. A tester en pré production avant de tout !
[correction_brand_address.sql.txt](https://github.com/thibaultvanc/playologie_exports/files/744956/correction_brand_address.sql.txt)

**Comment by thibaultvanc** [comment]
Executer ce code SQL corrige la base de donnée. A tester en pré production avant de tout !
correction_brand_address.sql.txt

**Comment by thibaultvanc** [comment]
sql a tester en preprod UNIQUEMENT : 
[correction_brand_address.sql.txt](https://github.com/thibaultvanc/playologie_exports/files/745026/correction_brand_address.sql.txt)

**Comment by Playologie** [comment]
Peut-on procéder en deux temps ?
1 > Identifier (générer une liste)
2 > Rectifier

**Comment by thibaultvanc** [comment]
fICHIER SQL ENTRE LES MAINS DE LUDOVIC
il va executer la requete en preprod pour que vous puissier tester
