### ISSUE TITLE
Tableaux dépassent de la feuille si bcp de tailles commandées

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#29]
Suite à l'ajout de la colonne prix unitaire, les tableaux sortent de la feuille

[moon monsters.pdf](https://github.com/thibaultvanc/playologie_exports/files/744444/moon.monsters.pdf)

**Comment by thibaultvanc** [comment]
ca depasse. mais ça viens pas du fait qu'on ai rajouté une colonne -

**Comment by thibaultvanc** [comment]
fait

**Comment by Playologie** [comment]
Pas encore visible quand on crée le pdf de cette facture :
t.brand@gmail.com / 1234
[c8b05d7d6908e7df5de2c7bd020f323e.pdf](https://github.com/thibaultvanc/playologie_exports/files/749979/c8b05d7d6908e7df5de2c7bd020f323e.pdf)

http://playologie.organit.fr/brand-invoice/#/invoice/2

**Comment by Playologie** [comment]
Pas ok de mon coté

[95492914aa17a48e6eaa02eca45438a6.pdf](https://github.com/thibaultvanc/playologie_exports/files/754231/95492914aa17a48e6eaa02eca45438a6.pdf)

**Comment by thibaultvanc** [comment]
OK, c'est fait

**Comment by thibaultvanc** [comment]
il faudrait tester avec une invoice ayant bcp de tailles. Mais sur l'exemple que l'on test depuis le debut c'est ok

**Comment by Playologie** [comment]
Produit coupé sur 2 tableaux "Chemise sans couleur" (premier de la facture) : Serait-il possible de ne pas répéter la partie nom du produit, réf, codes douaniers etc? Idem BL, commande...
![capture d ecran 2017-02-09 a 10 21 50](https://cloud.githubusercontent.com/assets/24650759/22776862/9baef2d0-eeb1-11e6-94de-2df82a766657.png)


[double tabeleau 259ef3a46eb702ea1b21b3897ee3cf9f.pdf](https://github.com/thibaultvanc/playologie_exports/files/763140/double.tabeleau.259ef3a46eb702ea1b21b3897ee3cf9f.pdf)

**Comment by thibaultvanc** [comment]
FAIT - PAS EN LIGNE

**Comment by thibaultvanc** [comment]
en ligne
