### ISSUE TITLE
Images un peu trop optimisées (floues/pixellisées), peut-on trouver un juste milieu ? Mais poids effectivement extrêmement réduit

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#3]

**Comment by thibaultvanc** [comment]
Besoin de savoir quel layout et si c'est l'image de pdt ou imprimé

**Comment by Playologie** [comment]
il s'agit de l'image produit

Concerne format 4perpages uniquement en fait, sinon pour les autres ratio qualité/poids très bien
[qualite cee5c666c2056ff613e9a3cac90b98b6.pdf](https://github.com/thibaultvanc/playologie_exports/files/763534/qualite.cee5c666c2056ff613e9a3cac90b98b6.pdf)

**Comment by thibaultvanc** [comment]
FAIT
