### ISSUE TITLE
Articles à 0 pour facture partielle

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#30]
Marque KidsFashionBrand 
kfb@playologie.com / kid2017

- Film : https://drive.google.com/file/d/0B9Zmb2lmy-4lYjFJaTA4UWNmZmc/view
- ID commande : 3530

Au moment de créer la 1ère facture, si je change des quantités (qui ne seront donc pas inclus dans cette facture), d'autres produits sont impactés et s'affichent à 0 alors qu'ils n'ont pas été touchés

[KidsFashionBrand INVOICE- 01022017-0005.pdf](https://github.com/thibaultvanc/playologie_exports/files/744650/KidsFashionBrand.INVOICE-.01022017-0005.pdf)

**Comment by thibaultvanc** [comment]
est-ce que ça marche après avoir sauvé ou rechargé la page ?
De mon coté je prends les éléménts de la base de données donc je ne vois pas trop comment je peux faire... A voir avec Ludovic

**Comment by Playologie** [comment]
KFB
kfb@playologie.com / kid2017

Commande
http://playologie.com/brand-order/#/order/3500

1ère facture créée en faisant des modifs avant clic sur CREATE -> apparition de quantités à 0 
http://playologie.com/brand-invoice/#/invoice/28
https://drive.google.com/file/d/0B9Zmb2lmy-4lcnd6LXNhTXExc1E/view

Puis 2e facture créée, sans aucun changement -> quantités à 0 aussi
http://playologie.com/brand-invoice/#/invoice/29
https://drive.google.com/file/d/0B9Zmb2lmy-4lVDNkd0JXbXNQQVE/view

[ INVOICE- 01022017-0007 .pdf](https://github.com/thibaultvanc/playologie_exports/files/745267/INVOICE-.01022017-0007.pdf)
[ INVOICE- 01022017-0008 .pdf](https://github.com/thibaultvanc/playologie_exports/files/745268/INVOICE-.01022017-0008.pdf)

**Comment by Playologie** [comment]
A vérifier : les histoires de 0 à la création de facture concernent je pense les articles sans couleur ni imprimés. la ligne de l'imprimé commandé est absente et donc la ligne de total (en gras) est à 0

**Comment by thibaultvanc** [comment]
fait
