### ISSUE TITLE
Au delà de 10/11 tailles dans le tableau : mise en page cassée (ça déborde)

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#34]
Il faut créer un 2e tableau dessous à partir de la 11e taille, sans répéter l'image produit mais on reprend les imprimés/couleurs, voir pdf actuel et le petit montage de simulation

Pas de total en bout de ligne sur le premier tableau. Total de l'ensemble de l'article, que sous le 2e tableau

![commande organit 014f73cdcd42b20171f17361ab05ad50-1](https://cloud.githubusercontent.com/assets/24650759/22551992/56c58206-e957-11e6-92c6-8ca25c11d899.jpg)

[commande organit 014f73cdcd42b20171f17361ab05ad50.pdf](https://github.com/thibaultvanc/playologie_exports/files/747870/commande.organit.014f73cdcd42b20171f17361ab05ad50.pdf)

**Comment by Playologie** [comment]
le tableau pour un article sans couleur ça passe, mais voir page 2 article avec des couleurs (imprimés c'est surement pareil) : le tableau déborde du filet, ainsi que le prix total produit en bas 

[Uploading 23c5565b3c7bb8cf540603020db2e224.pdf…]()

**Comment by Playologie** [comment]
dommage que les colonnes des couleurs soient pas calées à gauche pour etre bien l'une sous l'autre

**Comment by Playologie** [comment]
pour moi j'ai encore des décalages
cf les 2 PJ, dont PDF page 2
[2 tableaux 2e64a3f7e717cbaccc434ea14f787c03.pdf](https://github.com/thibaultvanc/playologie_exports/files/787831/2.tableaux.2e64a3f7e717cbaccc434ea14f787c03.pdf)
![capture d ecran 2017-02-20 a 16 08 59](https://cloud.githubusercontent.com/assets/24650759/23130505/0432b39a-f787-11e6-8a7b-afb094d41938.png)

**Comment by thibaultvanc** [comment]
corrigé - en ligne

**Comment by Playologie** [comment]
c'est plutôt pire :-)
Voir exemple sur 3 tableaux
http://playologie.organit.fr/export/order/d63561eeeb0144cab7cad6a0f3b29d68.pdf

**Comment by organitdev** [comment]
Fait commit#cc2f12886d5c8572224882957a4772e0b3553978

**Comment by Playologie** [comment]
Actuellement en prod, beaucoup mieux, mais deux remarques :
- est-il possible de décaler un tableau pour qu'il ne soit pas coupé et le commencer à la page suivante ?
- le  dernier bloc du tableau (tailles 19,20) se cale à gauche et les proportions semblent différentes, écrases, et le tableau au dessus a des décalages aussi, il faut qu'ils soient dans la continuité des blocs précédents.
Voir PJ

[a0ff9219b168a9ded9687dcd322024c5.pdf](https://github.com/thibaultvanc/playologie_exports/files/912598/a0ff9219b168a9ded9687dcd322024c5.pdf)

**Comment by thibaultvanc** [comment]
vous venez de générer l'excel sur organit.playologie ? 
moi, j'ai ce resultat : 
[84e51eb0959e51fa151cddd61f4a39d3 (1).pdf](https://github.com/thibaultvanc/playologie_exports/files/912927/84e51eb0959e51fa151cddd61f4a39d3.1.pdf)

**Comment by Playologie** [comment]
c'était en prod car vous me disiez que ça avait du passer. Je recommence sur organit

**Comment by organitdev** [comment]
[0877fc6f3267a6290c7328759484c114.pdf](https://github.com/thibaultvanc/playologie_exports/files/967569/0877fc6f3267a6290c7328759484c114.pdf)

Le dernier test fait donne ça
