### ISSUE TITLE
Facture : les totaux sont avec des décimales

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#35]
selon que c'est un imprimé ou une couleur ? voir ci-joint : 1280 vs 1280.00
[facture 30fa1f6e632d349ef3cc4eea44159983.pdf](https://github.com/thibaultvanc/playologie_exports/files/748156/facture.30fa1f6e632d349ef3cc4eea44159983.pdf)

**Comment by mikael-desharnais** [comment]
Ok fait
