### ISSUE TITLE
Zone de signature ne s'affiche pas alors qu'elle a été demandée dans les brand_doc

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#36]
[bon de livraison 30fa1f6e632d349ef3cc4eea44159983.pdf](https://github.com/thibaultvanc/playologie_exports/files/748162/bon.de.livraison.30fa1f6e632d349ef3cc4eea44159983.pdf)
[Uploading facture 30fa1f6e632d349ef3cc4eea44159983.pdf…]()

**Comment by thibaultvanc** [comment]
ceci avait été corrigé sur les Invoices - pas sur les BL
pouvez vous me confirmer que c'est ok pour les invoices ?

**Comment by Playologie** [comment]
oui, c'est bien pris en compte dans facture

**Comment by thibaultvanc** [comment]
fait pour BL

**Comment by Playologie** [comment]
quand je génère un BL la zone de signature ne s'affiche toujours pas alors qu'elle a été demandée

**Comment by Playologie** [comment]
zone de signature demandée pour les BL, elle ne s'affiche pas quand je génère un BL

**Comment by thibaultvanc** [comment]
FAIT - en ligne
