### ISSUE TITLE
Taille sans prix indiqué : ne pas l'afficher dans le tableau du produit commandé

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#37]
exemple t.brand@gmail.com / 1234

Commande :
http://playologie.organit.fr/brand-order/#/order/4

Chemise 3 / taille 12 -> aucun prix = la masquer

[e62154099496c848dce05cf644a4d30e.pdf](https://github.com/thibaultvanc/playologie_exports/files/748394/e62154099496c848dce05cf644a4d30e.pdf)

**Comment by thibaultvanc** [comment]
ok - un produit peut ne pas avoir de tailles - mais être commandé - dans ce cas, je ne l'affiche pas . merci de me confirmer

**Comment by Playologie** [comment]
c'est pas exactement ça, car un produit a au moins un taille :
- un produit est relié à une grille de tailles (par exemple une grille allant de XS à XXL) 
- il peut ne pas avoir de prix (et donc ne pas être proposé à la vente) dans une ou plusieurs des tailles de cette grille (disons pas de XS par exemple). Mais d'autres produits utilisant la même grille pourraient avoir un prix pour cette taille.
- il ne faut pas afficher la colonne XS (car pas de prix), la grille doit aller de S à XXL

**Comment by thibaultvanc** [comment]
ok, cela s'applique a commande uniquement ou aussi à invoice et BL ?

**Comment by Playologie** [comment]
c'est valable partout : commande, bl, facture et les factures à venir (export, pro forma)

**Comment by thibaultvanc** [comment]
FAIT

**Comment by thibaultvanc** [comment]
du coups, suite à notre conversation téléphonique (6 fev) -> le fait de ne pas afficher les produits qui n'ont pas de prix pour la taille represente un risque -> donc j'enlève la modification faite

**Comment by Playologie** [comment]
ne montrer dans tous les documents que les colonnes des tailles commandées

**Comment by thibaultvanc** [comment]
ne montrer dans tous les documents que les colonnes des tailles commandées : **fait**

order > par tel vous m'avez dit de ne pas afficher les imprimés ou couleurs qui ne son pas commandé 
(pour invoice et shipment, c'est déjà le cas) => **pas encore fait**

**Comment by thibaultvanc** [comment]
order => fait

**Comment by thibaultvanc** [comment]
en ligne
