### ISSUE TITLE
Ajouter réf de taille sous la taille

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#38]
![capture d ecran 2017-02-03 a 12 45 31](https://cloud.githubusercontent.com/assets/24650759/22590282/bb62fe3e-ea0e-11e6-821c-35aa56a62290.png)

**Comment by thibaultvanc** [comment]
fait

**Comment by Playologie** [comment]
vu, mais "agrandir et texte en noir" pas pris en compte (pas lisible actuellement à l'écran, et à l'impression à mon avis c'est pire). Arial Narrow par exemple si possible

**Comment by thibaultvanc** [comment]
on parle bien de la référencer de la taille ? car pour moi ceci est lisible, voir capture : https://i.gyazo.com/15294c202cb87b7135160985360256fd.png

**Comment by Playologie** [comment]
Oui, par exemple sur organit :

Collection 	Chemises
Article 		"Chemise 3"
Tailles		13,14,15…
Réf taille :	REF13, REF14, REF15





Schlomi MELKI
Project manager
PLAYOLOGIE.COM <http://www.playologie.com/>

PICAFLOR SARL
5, rue de la Plaine 75020 Paris
Tél : +33 1 43 72 75 37
Let's connect : Linkedin <https://fr.linkedin.com/pub/schlomi-melki/41/852/338> | Viadeo <http://www.viadeo.com/fr/profile/schlomimelki>
Facebook <https://www.facebook.com/playologie> | Twitter <http://twitter.com/playologie> | Pinterest <https://www.pinterest.com/playologie/> | Instagram <https://instagram.com/playologie/>

**Comment by Playologie** [comment]
je ne le vois dans aucun type de document, de quelle commande, BL ou facture vient votre capture ?

**Comment by thibaultvanc** [comment]
en ligne - la capture vient de facture

**Comment by Playologie** [comment]
- Ajouter aussi dans "BL"
- Dans "commande" : typo plus grande, en noir, arial narrow

**Comment by thibaultvanc** [comment]
fait Dans BL

**Comment by thibaultvanc** [comment]
en ligne
