### ISSUE TITLE
Corrections sur Remise bas de facture

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#39]
clés inversées et il manque le sigle % au bout du pourcentage de remise. cf PJ
![capture d ecran 2017-02-06 a 16 57 02](https://cloud.githubusercontent.com/assets/24650759/22654591/859aeaa6-ec8d-11e6-8179-962eabbc13d0.png)

**Comment by thibaultvanc** [comment]
fait pour les pdf order + invoice
//en ligne
