### ISSUE TITLE
Ajout TVA par produit

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#40]
Un oubli suite à l'évolution entre les gabarits et le développement. Chaque article peut avoir un taux de TVA qui lui est propre. Le bas de commande ne reproduit que le cumul en valeur de ces taux individuels. Donc il faut ajouter une ligne dans chaque tableau vers le total, cf PJ. Masquer la ligne quand TVA à 0
![capture d ecran 2017-02-06 a 17 31 54](https://cloud.githubusercontent.com/assets/24650759/22656080/70f17c28-ec92-11e6-9b09-9441859b6918.png)

**Comment by thibaultvanc** [comment]
fait - mais il faut que je vérifie si ça ca marche bien avec le discount 
**ne pas m'enlever des assignees. merci**

**Comment by Playologie** [comment]
Vu sur Invoice, ok. Entre chaque article une ligne comme ceci s'est ajouté : 
{{-- {{-- {{-- {{-- {{-- {{-- {{-- --}} {{-- --}} {{-- --}} {{-- --}} {{-- --}} 
[05431d27e56493b84b4b394bd8ed6290.pdf](https://github.com/thibaultvanc/playologie_exports/files/758041/05431d27e56493b84b4b394bd8ed6290.pdf)

**Comment by thibaultvanc** [comment]
ceci est corrigé

{{-- {{-- {{-- {{-- {{-- {{-- {{-- --}} {{-- --}} {{-- --}} {{-- --}} {{-- --}}

**Comment by thibaultvanc** [comment]
donc ticket doit etre ok
