### ISSUE TITLE
Catalogue : affichage des prix

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#41]
Plutot que d'afficher le prix plein de fois quand c'est le même, est-il possible de regrouper les tailles entre elles et n'afficher qu'un prix ?

Exemple. :
Avant :
S : USD 15.00, M : USD 15.00, L : USD 18.00

Après : 
S, M : USD 15.00, L : USD 18.00

**Comment by thibaultvanc** [comment]
Fait sur le layout 1. Si c'est ok, je passe aux autres. voici le catalogue avec la modif : 
[2f253c5030a59800866fee0fab880cc1.pdf](https://github.com/thibaultvanc/playologie_exports/files/760349/2f253c5030a59800866fee0fab880cc1.pdf)

**Comment by thibaultvanc** [comment]
sur tous les layouts => ok
