### ISSUE TITLE
Migration : ordre des tailles

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#44]
Les tailles de chaque grille avaient un ordre défini en V1, ça na pas été transféré en V2.
En V2 on les trouve dans PLAY_brand_size > order

**Comment by thibaultvanc** [comment]
Ces informations ont été migrées mais j'ai besoin d'avoir un exemple car on avait plusieurs cas. Sans cas précis, se sera compliqué

**Comment by Playologie** [comment]
Testable en préprod

Marque	
Aghi e Bubi 

Nouvelle Collection 
Winter 2017

Produit
GIRL ORIGAMI SKIRT

Utilise la grille 
Linea Bimba (divisée en 2 groupes de prix)

Linea Bimba 3 - 5 anni
2 Anni
3 Anni
4 Anni
5 Anni

Linea Bimba 6 - 13 anni
6/7 Anni
8/9 Anni
10/11 Anni
12/13 Anni


La grille s'affiche dans l'ordre dans la gestion des grilles de tailles 
http://preprod3.playologie.com/brand-param/#/size

La grille s'affiche dans l'ordre dans l'édition d'article
http://preprod3.playologie.com/brand-collection-product/#/20791

La grille s'affiche dans le **DESORDRE** dans la preview d'article 
http://preprod3.playologie.com/buyer-brand-collection-product/#/20791

En désordre aussi coté acheteur (wallis@playologie.com / wallis0206) : 
- tailles listées au survol de l'article dans la liste des articles
http://preprod3.playologie.com/buyer-brand-collection/#/547

- dans le tableau sur la fiche article
http://preprod3.playologie.com/buyer-brand-collection-product/#/20791

**Comment by thibaultvanc** [comment]
Les données ont été migrées telles quelles et sont donc bonnes.
Si les informations sont bien triées dans la V2 à certains endroits et pas à d'autres, il s'agit clairement d'un problème dans la V2 et pas d'un problème de migration. Voir avec Ludovic
