### ISSUE TITLE
Caractères rajoutés à la migration

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#45]
Lors de la migration, les lignes dans les tables ne sont pas bien importée et contiennent des caractères spéciaux (ici un « CR » ). Des requêtes de Ludovic ne passaient pas du coup.

J'ai nettoyé à la main la bdd de prod pour les états américains, merci de ne pas écraser ça. Mais il faut nettoyer tous les autres états. Pour moi c'est surtout cette table mais vérifier qu'il n'y a pas eu d'autres caractères ajoutés dans d'autres tables

![cr image001](https://cloud.githubusercontent.com/assets/24650759/22794160/73ddf878-eef2-11e6-919d-06f61e5644d9.png)

**Comment by thibaultvanc** [comment]
C'était en V1.

**Comment by thibaultvanc** [comment]
Requête :
UPDATE `PLAY_country_state` SET `name`=REPLACE(`name`,'\r','')

**Comment by thibaultvanc** [comment]
FAIT
