### ISSUE TITLE
Descendre la taille de font pour N° de commande / de facture / de BL + Date

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#47]
ça reste trop gros et descend sur 2 lignes

![capture d ecran 2017-02-10 a 14 18 29](https://cloud.githubusercontent.com/assets/24650759/22828130/f0ee50e8-ef9b-11e6-9a06-8937cebbbc1d.png)

**Comment by thibaultvanc** [comment]
fait - en ligne
