### ISSUE TITLE
Logo de marque

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#48]
Dans les pages intérieures de catalogue : utiliser le logo de la marque (le même que dans les PDF de commande, facture...) et non l'image de profil (utilisé en couverture)

**Comment by thibaultvanc** [comment]
**Fait** sur tous les catalogues
par contre je ne vois pas comment changer le logo sur le site pour tester -  mais j'ai mis le même que pour les invoices

**en ligne**

**Comment by Playologie** [comment]
C'est bon !

Pour info : 
Le visuel illustrant la marque dans chaque univers se met ici :
http://playologie.organit.fr/brand-param/#/brand

Le logo pour les documents se met ici (actuellement bug si vous essayez de mettre une nouvelle image, mais il y a dejà une image actuellement) :
http://playologie.organit.fr/brand-account/#/doc

Je n'ai pas cloturé, juste pour que vous voyez ce commentaire, sinon c'est à cloturer

**Comment by thibaultvanc** [comment]
ok
