### ISSUE TITLE
masquer mention "pas de couleur ou imprimé"

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#49]
Laisser la zone vide
![capture d ecran 2017-02-14 a 15 35 03](https://cloud.githubusercontent.com/assets/24650759/22967347/66cbb4e0-f366-11e6-985a-fa4db574409a.png)

**Comment by thibaultvanc** [comment]
Fait - en ligne

**Comment by Playologie** [comment]
si possible fermer la cellule à droite
![Uploading Capture d’écran 2017-02-15 à 17.52.26.png…]()

**Comment by thibaultvanc** [comment]
fait
