### ISSUE TITLE
espace alloué aux références

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#53]
l’espace pour la référence est un peu court, ça tombe sur 2 lignes
exemple ici
[4f30a11a7bb5672bbad8adc5f5f9e850.pdf](https://github.com/thibaultvanc/playologie_exports/files/780726/4f30a11a7bb5672bbad8adc5f5f9e850.pdf)
 pour « ch3 15T 6coul »

**Comment by Playologie** [comment]
Pour moi c'est toujours le cas, pdf généré ce jour.
[organit 090f30e7230053f623b49cda0e39148a.pdf](https://github.com/thibaultvanc/playologie_exports/files/796059/organit.090f30e7230053f623b49cda0e39148a.pdf)

**Comment by organitdev** [comment]
Normalement c'est bon commit#6006c562f14ab431fbb3ffb3fd0c2e399eeafb50

**Comment by Playologie** [comment]
Ok, mais le ticket suivant reste important à régler :
Au delà de 10/11 tailles dans le tableau : mise en page cassée (ça déborde) #34
https://github.com/thibaultvanc/playologie_exports/issues/34

Contactez moi quand vous avez fini les dossiers d'inscription playoogie pour avancer sur les exports

Merci


Schlomi MELKI
Project manager
PLAYOLOGIE.COM

PICAFLOR SARL
5, rue de la Plaine 75020 Paris
Tél : +33 1 43 72 75 37
Let's connect : Linkedin | Viadeo
Facebook | Twitter | Pinterest | Instagram

**Comment by thibaultvanc** [comment]
ticket 34 fait depuis 10j
