### ISSUE TITLE
Afficher nombre total d'unités

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#54]
Un oubli qui remonte de la part des clients, besoin d'afficher le total d'unités en bas du BL.
C'est pas un champ d'option "brand doc" donc à afficher automatiquement dans tous les BL, de cette façon (en première ligne plutot qu'en dessous en fait):

![capture d ecran 2017-02-20 a 12 08 09](https://cloud.githubusercontent.com/assets/24650759/23122624/4761af3a-f765-11e6-8f7f-82f5f946165f.png)

**Comment by thibaultvanc** [comment]
fait
http://playologie.organit.fr/export/shipment/521ad5bc0cc47466c1f7d57054677543.pdf
