### ISSUE TITLE
Titre des factures Pro forma

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#56]
Il faut qu'on appelle ces documents "Facture pro forma" et non "Facture"
Je n'ai pas de clé qui dise "Facture pro forma" mais seulement des "pro forma" seuls. Il vous est possible d'en rajouter une ?

[organit 090f30e7230053f623b49cda0e39148a.pdf](https://github.com/thibaultvanc/playologie_exports/files/796068/organit.090f30e7230053f623b49cda0e39148a.pdf)

**Comment by thibaultvanc** [comment]
FAIT - en ligne
