### ISSUE TITLE
PDF Facture : prix, totaux

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#59]
testé sur organit

Marque t.brand
crée compte + commande pour testorga56413546874684@yopmail.com

Commande 
http://playologie.organit.fr/brand-order/#/order/5
45,349.48 EUR

Facture partielle
http://playologie.organit.fr/brand-invoice/#/invoice/new/5
29,490.47 EUR

PDF
Prix puisés dans la mauvaise grille tarifaire 
Exemple Chemise 1 = 200 EUROS. Le PDF prend 100.00 EUR (car en fait dans l'autre grille c'est 100 $)
Total dans PDF erronnée : 45,349.48 EUR

**Comment by thibaultvanc** [comment]
fait - EN LIGNE
