### ISSUE TITLE
Facture d'export PDF > brand doc

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#60]
Préprod
mfb@playologie.com / man2017
http://preprod3.playologie.com/brand-order/#/shipment/22

Toutes les options Brand doc étaient cochées, mais problèmes dans les infos produit 

> EAN code s'affiche 2 fois
> Code MID Fabricant : info manquante dans le PDF
> Manufacturer's address : le pdf affiche le n° de fax s'affiche au lieu de l'adresse 
> Après création de la facture d'export j'ai ajouté un poids à un article, le poids total du BL fait 44kg, or le PDF affiche un total de 0 alors que le produit "Long sleeve Charisme" affiche bien "22000 g"

**Comment by Playologie** [comment]
- L'unité de poids doit être la même entre celle des articles à l'unité et le total en bas de document Ici garder le gramme par exemple. Donc afficher 2200 g et pas 22.
- Ajouter le nom de l'unité comem après chaque poids unitaire de chaque article

**Comment by thibaultvanc** [comment]
**fait,**
mais votre 2e point est le mete que le premier, il me semble ?

**Comment by Playologie** [comment]
j'ai voulu en re-générer sur organit mais le contenu des BL est vide pour les 2 BL existants actuellement sur le compte t.brand.
Impossible de valider une commande en cours "fraiche" 
(par exemple celle ci : http://playologie.organit.fr/brand-order/#/order/7)

D'une part je voulais dire de garder une homogénéité sur l'unité de poids, prendre celel définie par le client + toujours afficher le nom de l'unité de poids après chaque poids affiché (dans chaque produit et dans les totaux), à savoir g, kg, oz, etc...
