### ISSUE TITLE
Contenu Avoir erroné coté Acheteur ET Marque

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#62]
Préprod  
Acheteur : wallis@playologie.com / wallis0206
marque : mfb@playologie.com / man2017

L’avoir que l’acheteur ouvre en PDF est erronné :
> N° de l'avoir erroné (affiche une réf de facture INV-280217-003 au lieu de "-")
> L'avoir ne contient que 3 articles, le PDF affiche plusieurs articles mais je ne sais pas à quoi correspndent-ils (une autre facture, une autre commande?)
> Le bas de l’avoir est un bas de facture venant d’ailleurs (les montants sont pas les bons, ils n’ont pas le sign moins devant, on y mentionne un acompte, commentaire de facture…)
[avoir wallis 3672e5a21917b7fe481539d66925d162.pdf](https://github.com/thibaultvanc/playologie_exports/files/827691/avoir.wallis.3672e5a21917b7fe481539d66925d162.pdf)

**Comment by thibaultvanc** [comment]
corrigé
