### ISSUE TITLE
Facture ProForma ne s'ouvre pas

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#63]
Pré prod 
wallis@playologie.com / wallis0206
Elle s'ouvre bien coté marque
![capture d ecran 2017-03-08 a 14 46 37](https://cloud.githubusercontent.com/assets/24650759/23706340/13aa4bf6-040e-11e7-9d3f-f5fa1fd213b1.png)

Exemple commande MFB-240117-000
http://preprod3.playologie.com/buyer-order/#/3382

**Comment by thibaultvanc** [comment]
FAIT en local - mais pb de synchronisation
