### ISSUE TITLE
Catalogue PDF : un peu trop compressé

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#64]
Pour ce template là (vertical, 6 articles/page) le résultat est trop compressé. Si vous utilisez l'image small , prendre l'image medium, si medium prendre le large, ou alors moins compresser
[TC 6P 0df049726f26c0163f0a3ab6c93a1f02.pdf](https://github.com/thibaultvanc/playologie_exports/files/828163/TC.6P.0df049726f26c0163f0a3ab6c93a1f02.pdf)

**Comment by organitdev** [comment]
Corrigé : commit#083a6b9fa1c54905734cd58a7d2a2f33929b31c6

**Comment by thibaultvanc** [comment]
fait
