### ISSUE TITLE
Modèle export Excel des commandes

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#65]
Remarques suite envoi skype du fichier 433d3194b06e65a5f338fbdc5f60d0e3.xlsx le 23/03/2017 à 16h04 :

- Order Status > mettre le libellé et non l'ID
- Account number > d'ou tirez vous ce chiffre ? Je ne vois pas ce n° de client dans la fiche client 
- Civility > Mettre selon la langue mais pas just f ou m : M, Mme (en français) Mr, Mrs (anglais), prendre dans les clés
- Billing state > laisser vide pour les états "is_state" = 0
- Shipping state > laisser vide pour les états "is_state" = 0
- Base price, tax excluded > c'est le HT général de la commande et non celui d'un article précis (Chemise 1), pour cette commande (ID 5) c'est donc 44,772.00 EUR
- Size ref > laisser vide quand pas de données
- Color/Print name > l'ID est inutile, il faut absilument le libellé de l'imprimé/couleur...
- Discount amount > Mettre 0 quand pas de remise

**Comment by thibaultvanc** [comment]
Order Status > mettre le libellé et non l'ID = **fait**
Account number > d'ou tirez vous ce chiffre ? Je ne vois pas ce n° de client dans la fiche client **Pour le moment, je l'enleve**
Civility > Mettre selon la langue mais pas just f ou m : M, Mme (en français) Mr, Mrs (anglais), prendre dans les clés **FAIT**
Billing state > laisser vide pour les états "is_state" = 0 **FAIT**
Shipping state > laisser vide pour les états "is_state" = 0 **FAIT**
Base price, tax excluded > c'est le HT général de la commande et non celui d'un article précis (Chemise 1), pour cette commande (ID 5) c'est donc 44,772.00 EUR
Size ref > laisser vide quand pas de données **fait**
Color/Print name > l'ID est inutile, il faut absilument le libellé de l'imprimé/couleur... **fait**
Discount amount > Mettre 0 quand pas de remise **fait**

**Comment by thibaultvanc** [comment]
J'ai un grous doute sur account number

**Comment by Playologie** [comment]
Je me base sur la commande d'origine : http://playologie.organit.fr/brand-order/#/order/5

- Account number : l'info doit provenir de la table 'PLAY_brand_buyer' > champ "ref"
- Base price, tax excluded > c'est le HT général de la commande et non celui d'un article précis (Chemise 1), pour cette commande (ID 5) c'est donc 44,772.00 EUR
- Erreur : champ Size : mettre le libellé de la taille (par exemple "S", "M", etc)
- Champ "size ref" : laisser vide quand pas de données (actuellement il contient la "size" et la "size" contient un ID je pense)

**Comment by Playologie** [comment]
Commande brouillon http://playologie.organit.fr/brand-order/#/order/4
- Colonne date de commande : mettre la date seule, sans l'heure
- Une commande brouillon n'a normalement pas de n° : ne rien mettre. C'est le n° de client qui a été placé ici.
- Account number : c'est l'ID qui s'affiche alors qu'il faut afficher 345678 (la réf donnée par la marque en inscrivant l'acheteur)
- Billing state : enlever les ** dans le libellé de la colonne
- Base price, tax excluded : le champ est vide dans l'excel au lieu d'afficher 8,409.24
- Colonne AH : désolé mais en fait cette colonne n'a pas lieu d'etre : il y a un taux de TVA par article, ou pour le transport, mais pas de TVA globale à la commande
- Colonne AK "Total" : ne pas mettre un 3e chiffre après la décimale : 9250,16 et non 9250,164
- AO / Size : cette colonne doit afficher le noms des tailles : 12,13,14 etc et non un ID
- AP / Size ref : cette colonne devrait etre afficher les chiffres 30 ou 40 (réf de taille) et non les tailles elles mêmes
- AU / Discount amount : montant erroné : 2% de 50 devrait faire 1, 9% de 44 devrait faire 40,04
- AW / VAT amount : montant erronné : 10% de 49 [50 - 2% de remise] = 4,9
[2560b565edbaf81429d789d9c858674b.xlsx](https://github.com/thibaultvanc/playologie_exports/files/920199/2560b565edbaf81429d789d9c858674b.xlsx)

**Comment by Playologie** [comment]
http://playologie.organit.fr/brand-order/#/order/5

- Tri : si possible trier par produit puis par couleur puis par taille (actuellement c'est l'inverse : tailles puis couleur)
- AQ : manque les noms des imprimés (carreaux, carreaux2, color 1...)
[b15bac4c67632cca20dd021c4c3eadba.xlsx](https://github.com/thibaultvanc/playologie_exports/files/922225/b15bac4c67632cca20dd021c4c3eadba.xlsx)

**Comment by thibaultvanc** [comment]
Colonne date de commande : mettre la date seule, sans l'heure **fait**
Une commande brouillon n'a normalement pas de n° : ne rien mettre. C'est le n° de client qui a été placé ici. **fait**
Account number : c'est l'ID qui s'affiche alors qu'il faut afficher 345678 (la réf donnée par la marque en inscrivant l'acheteur)**fait**
Billing state : enlever les ** dans le libellé de la colonne **fait**
Base price, tax excluded : le champ est vide dans l'excel au lieu d'afficher 8,409.24 **fait**
Colonne AH : désolé mais en fait cette colonne n'a pas lieu d'etre : il y a un taux de TVA par article, ou pour le transport, mais pas de TVA globale à la commande**fait**
Colonne AK "Total" : ne pas mettre un 3e chiffre après la décimale : 9250,16 et non 9250,164 **fait**
AO / Size : cette colonne doit afficher le noms des tailles : 12,13,14 etc et non un ID
AP / Size ref : cette colonne devrait etre afficher les chiffres 30 ou 40 (réf de taille) et non les tailles elles mêmes **fait**
AU / Discount amount : montant erroné : 2% de 50 devrait faire 1, 9% de 44 devrait faire 40,04 **fait**
AW / VAT amount : montant erronné : 10% de 49 [50 - 2% de remise] = 4,9 **fait**

**Comment by thibaultvanc** [comment]
Tri : si possible trier par produit puis par couleur puis par taille (actuellement c'est l'inverse : tailles puis couleur) **=> compliqué, moi dites moi si c'est necessaire**

manque les noms des imprimés (carreaux, carreaux2, color 1...) : **fait**

**Comment by Playologie** [comment]
Test sur http://playologie.organit.fr/brand-order/#/order/2 :
- Le préfixe et n° de tél sont vides (ça devrait être : +33 638616548 ). Colonnes R et S
Bizarrement c'est pas le cas avec une commande brouillon http://playologie.organit.fr/brand-order/#/order/4
