### ISSUE TITLE
PDF de commande / de facture inaccessible

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#66]
Marque db@Schlomi MELKI.com (en prod): nous ne pouvions plus accéder aux commandes et aux factures (loader en boucle), et Ludovic a résolu le problème qui venait du fait que la marque avait supprimé une devise (soft delete). Mais à présent on ne peut plus accéder aux pdf et Ludovic nous dit que ce soft delete sur devise est une chose à prendre également en compte de votre côté et à corriger dans votre partie de code.
peut etre valable aussi sur proforma et facture de douance car ils contiennent des montants et donc des devises

**Comment by thibaultvanc** [comment]
besoin qu'on en discute par téléphone
