### ISSUE TITLE
PDF COmmande

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#67]
En bas de commande :
- c'est pas "Conditions de paiement" mais "Délai de paiement (pour ce champ là), le champ conditions de paiement c'est un autre
- c'est pas "Adresse de livraison" mais "conditions de livraison"

Exemple de la PJ en préprod 
http://preprod3.playologie.com/brand-order/#/order/3642
mfb@playologie.com / man2017

**Comment by thibaultvanc** [comment]
corrigé
