### ISSUE TITLE
PDF des commandes avec articles sans quantités

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#69]
Désormais dans les étapes précédant sa validation, la commande peut circuler avec des articles sans quantités. Il faut que le PDF le prenne en compte, actuellement dans les PDF ça fait sauter les couleurs/imprimés et "HH" apparait dans les zones de quantités

Vous pouvez voir un exemple en préprod
Marque ManFashionBrand
mfb@playologie.com
mot de passe man2017

Je précise qu'il peut y avoir un mélange d'article avec et sans quantités. Ce n'est que lors de la validation finale de la commande que les articles sans quantités seront supprimés (développement encore en cours par Ludovic, la préprod n'est pas finie)

Lien direct vers la commande "en cours"
http://preprod3.playologie.com/brand-order/#/order/3744

**Comment by Ecllyps** [comment]
cela me semble bien

**Comment by Ecllyps** [comment]
Je ne connais pas le process de cloture
