### ISSUE TITLE
La zone signature s'ajoute, même quand on ne l'a pas sélectionné dans brand_doc (field_sign)

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#7]

**Comment by thibaultvanc** [comment]
fait sur invoice uniquement, c'est le seu endroit ou l'on a le cadre signature

**Comment by Playologie** [comment]
Le bon de livraison a aussi une zone signature et l'option dans brand_doc, actuellement même quand coché dans brand_doc l'encadré ne s'affiche pas dans bon de livraison

**Comment by thibaultvanc** [comment]
Rajouté pour les BL
