### ISSUE TITLE
écran "select brand"

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#70]
1- la poubelle noire est à placer au même niveau que le nom de la marque et sans cadre rouge autour d'elle (voir maquette ci-dessous)

![poubelle1](https://cloud.githubusercontent.com/assets/24650759/26011496/9d3a58ae-3751-11e7-8422-7a6fae4870c3.jpg)

2 - le clic sur la poubelle amène sur une popin qui indique que l'on va supprimer la marque, mais le clic sur ok n'a pas d'effet. Si c'est parce qu'il n'y a qu'une seule marque, alors il ne doit pas y avoir de poubelle lorsqu'il n'y a qu'une seul marque.

<img width="980" alt="popin" src="https://cloud.githubusercontent.com/assets/24650759/26011707/746c9512-3752-11e7-956c-b1e2709a1da6.png">

3 - le clic sur "cancel" fait apparaître une alerte "delete canceled" en haut de l'écran --> supprimer cette alerte, elle n'est pas utile
<img width="694" alt="capture d ecran 2017-05-12 a 20 15 18" src="https://cloud.githubusercontent.com/assets/24650759/26011753/9ce9488c-3752-11e7-83f5-f7f9f9191a5e.png">

4 - lorsqu'il y a 0 marques et que l'on clique sur suivant, on arrive sur une page sur laquelle il n'y a plus que le bouton "save for later" et on est bloqué --> il faut une alerte pour dire qu'il faut au moins une marque et ne pas pouvoir aller sur une autre page sans marque.

<img width="959" alt="capture d ecran 2017-05-12 a 20 37 00" src="https://cloud.githubusercontent.com/assets/24650759/26011945/3fb31f66-3753-11e7-9a8f-2338f251d8f3.png">

5 - la poubelle pays doit être bien plus proche du pays (voir maquette ci-dessous)
![poubelle_pays](https://cloud.githubusercontent.com/assets/24650759/26012108/b5431d3a-3753-11e7-9e0b-ea2e14dc2f08.jpg)

6 - le clic sur la poubelle du pays supprime la marque!

7 - la phrase "Select here your brand to represent" n'est probablement pas une clé (voir image ci-dessous). Aussi mettre "if you can't find your brand" sur la même ligne que le bouton "+ create brand":

<img width="649" alt="capture d ecran 2017-05-12 a 20 44 47" src="https://cloud.githubusercontent.com/assets/24650759/26012224/21ae8f22-3754-11e7-9a65-6f1a851aa410.png">

8 - supprimer sur tous les écrans le logo playologie derrière les titres pour réduire significativement l'espace utilisé en haut de page

**Comment by thibaultvanc** [comment]
1- la poubelle noire est à placer au même niveau que le nom de la marque et sans cadre rouge autour d'elle **FAIT**

2 - le clic sur la poubelle amène sur une popin qui indique que l'on va supprimer la marque, mais le clic sur ok n'a pas d'effet. Si c'est parce qu'il n'y a qu'une seule marque, alors il ne doit pas y avoir de poubelle lorsqu'il n'y a qu'une seul marque.  **FAIT**

3 - le clic sur "cancel" fait apparaître une alerte "delete canceled" en haut de l'écran --> supprimer cette alerte, elle n'est pas utile  **FAIT**

4 - lorsqu'il y a 0 marques et que l'on clique sur suivant, on arrive sur une page sur laquelle il n'y a plus que le bouton "save for later" et on est bloqué --> il faut une alerte pour dire qu'il faut au moins une marque et ne pas pouvoir aller sur une autre page sans marque.  **FAIT**

5 - la poubelle pays doit être bien plus proche du pays (voir maquette ci-dessous)
poubelle_pays  **FAIT**

6 - le clic sur la poubelle du pays supprime la marque!  **FAIT**

7 - la phrase "Select here your brand to represent" n'est probablement pas une clé (voir image ci-dessous). Aussi mettre "if you can't find your brand" sur la même ligne que le bouton "+ create brand": **FAIT**
**cle ajoutée dans Web.php > representation > selectBrandToRepresent**

8 - supprimer sur tous les écrans le logo playologie derrière les titres pour réduire significativement l'espace utilisé en haut de page
**FAIT dîtes moi si je doit encore gagner de l'espace**

**Comment by Playologie** [comment]
- point 2 : le clic sur la poubelle devant le nom de la marque ne fonctionne pas

- point 8 : ok si on garde le logo plus petit mettre quand même le titre dessus + voir autres points sur maquette

![blabla](https://cloud.githubusercontent.com/assets/24650759/26047725/945eafe6-3954-11e7-85d8-a83e89b967ce.jpg)

**Comment by thibaultvanc** [comment]
FAIT

**Comment by Playologie** [comment]
non, la poubelle pour supprimer la marque est toujours inactive
