### ISSUE TITLE
écran "choose plan"

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#71]
1 - l'alerte en bas de page "please check the errors..." ne peut t'elle apparaître que s'il y a effectivement des erreurs?
<img width="958" alt="capture d ecran 2017-05-12 a 20 53 29" src="https://cloud.githubusercontent.com/assets/24650759/26013517/1a8aed08-3759-11e7-86f0-f93133e70e5a.png">

2 - Supprimer le "1" devant "brand name"?
3 - masquer partout les "login" et "register" dans le bandeau supérieur de la page
4 - masquer partout les "proudly larastraped..." en bas de page
5 - dans l'écran ci-dessous, supprimer le "php 1050" avec son refresh
<img width="851" alt="capture d ecran 2017-05-12 a 21 24 50" src="https://cloud.githubusercontent.com/assets/24650759/26013623/931aed40-3759-11e7-9202-cf36eb7c9f57.png">

**Comment by thibaultvanc** [comment]
1 - l'alerte en bas de page "please check the errors..." ne peut t'elle apparaître que s'il y a effectivement des erreurs? **FAIT**


2 - Supprimer le "1" devant "brand name"?  **FAIT**
3 - masquer partout les "login" et "register" dans le bandeau supérieur de la page   **FAIT**
4 - masquer partout les "proudly larastraped..." en bas de page   **FAIT**
5 - dans l'écran ci-dessous, supprimer le "php 1050" avec son refresh  **FAIT**

**Comment by thibaultvanc** [comment]
FAIT

**Comment by Playologie** [comment]
point 2 : oui sur cet écran mais ça n'est pas fait sur l'écran précédent

**Comment by thibaultvanc** [comment]
Fait
