### ISSUE TITLE
écran "billing information"

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#72]
1- "contact_name" n'est probablement pas une clé. De plus, est-ce que ça ne doit pas être company name? Noter que l'on retrouve ce même contact_name dans l'écran "Welcome".
<img width="887" alt="capture d ecran 2017-05-12 a 21 28 46" src="https://cloud.githubusercontent.com/assets/24650759/26013737/0b85f18a-375a-11e7-809c-f6b381aabac3.png">
2 - "email_confirmation" n'est probablement pas une clé
<img width="800" alt="capture d ecran 2017-05-12 a 21 34 07" src="https://cloud.githubusercontent.com/assets/24650759/26013974/e17236a0-375a-11e7-9374-268577be3a7c.png">
3 - salutation indique par défaut "Mme" alors que je suis en anglais. Aussi lorsque l'on change d'écran et que l'on revient à celui-ci, je vois toujours Mme alors que j'avais changé pour Mss.
<img width="543" alt="capture d ecran 2017-05-12 a 21 35 52" src="https://cloud.githubusercontent.com/assets/24650759/26014009/0f907d1c-375b-11e7-8565-eaf3007f4dec.png">
4 - "state" ne devait apparaître que pour certains pays. Ok pour qu'on le mette pour tous, mais il faut supprimer l'étoile (de toutes façons, ça n'est déjà pas obligatoire!)
<img width="814" alt="capture d ecran 2017-05-12 a 21 37 03" src="https://cloud.githubusercontent.com/assets/24650759/26014064/603c42e6-375b-11e7-871b-47b24e69b0e6.png">
5 - lorsque l'on retire le Zip code et que l'on clique sur "next", ça mouline sans fin. Idem si l'on vide le champs "address". Tous les autres champs ok, une alerte apparaît bien.
<img width="995" alt="capture d ecran 2017-05-12 a 21 39 48" src="https://cloud.githubusercontent.com/assets/24650759/26014120/9aefcf34-375b-11e7-93e2-5f3c89bee389.png">

**Comment by thibaultvanc** [comment]
1- "contact_name" n'est probablement pas une clé. De plus, est-ce que ça ne doit pas être company name? Noter que l'on retrouve ce même contact_name dans l'écran "Welcome".
**remplacé par company name > ok**

2 - "email_confirmation" n'est probablement pas une clé
**c'est une cle dans le fichier "contactPerson.php"**

3 - salutation indique par défaut "Mme" alors que je suis en anglais. Aussi lorsque l'on change d'écran et que l'on revient à celui-ci, je vois toujours Mme alors que j'avais changé pour Mss. **Corrigé**

4 - "state" ne devait apparaître que pour certains pays. Ok pour qu'on le mette pour tous, mais il faut supprimer l'étoile (de toutes façons, ça n'est déjà pas obligatoire!)  **Corrigé**

5 - lorsque l'on retire le Zip code et que l'on clique sur "next", ça mouline sans fin. Idem si l'on vide le champs "address". Tous les autres champs ok, une alerte apparaît bien. **Corrigé**

**Comment by thibaultvanc** [comment]
fait

**Comment by Playologie** [comment]
- évoqué au tel à l'instant: company name ne doit pas être modifiable (aussi sur écran Welcome)

- point 5 : ok pour le ZIP code, mais pour l'adresse lorsque je la retire, j'ai bien un message d'alerte et ensuite si je la remets, le bouton next reste grisé.

**Comment by thibaultvanc** [comment]
évoqué au tel à l'instant: company name ne doit pas être modifiable (aussi sur écran Welcome)
**FAIT**

point 5 : ok pour le ZIP code, mais pour l'adresse lorsque je la retire, j'ai bien un message d'alerte et ensuite si je la remets, le bouton next reste grisé.
**FAIT**
