### ISSUE TITLE
écran "billing detail"

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#73]
1- masquer le "php 1050" avec son bouton refresh

<img width="766" alt="capture d ecran 2017-05-12 a 21 46 33" src="https://cloud.githubusercontent.com/assets/24650759/26014368/8822b2c6-375c-11e7-9cb1-1850e4a0b006.png">

2 - lorsque 'on change d'écran et que l'on revient à celui-ci, tout le contenu de "message to..." n'apparaît plus.

<img width="889" alt="capture d ecran 2017-05-12 a 22 08 23" src="https://cloud.githubusercontent.com/assets/24650759/26015051/8a51caac-375f-11e7-945b-a54f770d0830.png">

3 - lorsque l'on a la possibilité de payer en plusieurs fois, voir erreur dans les 2 écrans ci-dessous

<img width="778" alt="capture d ecran 2017-05-13 a 23 04 16" src="https://cloud.githubusercontent.com/assets/24650759/26029260/f82747e2-3830-11e7-929d-9637484fd0b8.png">

<img width="790" alt="capture d ecran 2017-05-13 a 23 04 32" src="https://cloud.githubusercontent.com/assets/24650759/26029262/fdfa444e-3830-11e7-817e-041aac782c81.png">

**Comment by thibaultvanc** [comment]
1- masquer le "php 1050" avec son bouton refresh
**FAIT**


2 - lorsque 'on change d'écran et que l'on revient à celui-ci, tout le contenu de "message to..." n'apparaît plus.**corrigé**

3 - lorsque l'on a la possibilité de payer en plusieurs fois, voir erreur dans les 2 écrans ci-dessous
**corrigé**

**Comment by Playologie** [comment]
- point 2 : toujours pas, j'ai écrit un message, suis passé à l'écran suivant puis revenu et message effacé

**Comment by Playologie** [comment]
je note aussi que si je sélectionne credit card, que je fais "next" puis que je fais "back", c'est bank wire qui est sélectionné

**Comment by thibaultvanc** [comment]
message playologie > **reparé**

je note aussi que si je sélectionne credit card, que je fais "next" puis que je fais "back", c'est bank wire qui est sélectionné
**reparé**
