### ISSUE TITLE
écran "payment"

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#74]
1 - les clés pour expiration date et CVV sont manquantes
2 - sur un petit écran, le cadre de droite déborde.
3 - mettre les icône en plus petit et sans déformation
<img width="981" alt="capture d ecran 2017-05-12 a 21 54 12" src="https://cloud.githubusercontent.com/assets/24650759/26014647/cc4748c6-375d-11e7-8663-92b2977f17ec.png">

**Comment by thibaultvanc** [comment]
1 - les clés pour expiration date et CVV sont manquantes
**FAIT** - les cles sont les suivantes : 
Web.php > billing > credit_card >month_placeholder
Web.php > billing > credit_card >year_placeholder
Web.php > billing > credit_card >cv_placeholder


2 - sur un petit écran, le cadre de droite déborde. 
**FAIT**

3 - mettre les icône en plus petit et sans déformation
**FAIT**

**Comment by Playologie** [comment]
ok pour tous les points, mais je note que l'on peut passer à l'écran suivant sans avoir rempli tous les champs (d'ailleurs même sans avoir rien rempli!)

**Comment by thibaultvanc** [comment]
Oui, vous pouvez passez si vous n'avez rien rempli => sauf si j'ai alias de monetico en base de données
ce qui me parait cohérant ..

**Comment by Playologie** [comment]
si on a un alias, alors les champs devraient être remplis avec des petites étoiles et on pourrait alors passer, mais si rien n'est rempli nos client pourraient valider le dossier sans numéro de CB? on perd du temps pour la suite, non?
