### ISSUE TITLE
écran "thank you 1"

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#75]
1 - supprimer toute la ligne "thank you for your registration..."
2 - la phrase "I declare..." déborde du cadre
3 - la case ne doit pas être par défaut cochée
4 - "link to Terms and Conditions" doit être au dessus de "I declare..." et doit ouvrir les CGV dans une nouvelle fenêtre et non pas dans la même.
5 - le clic sur "previous" m'a ramené à la phase 1 du process d'inscription
<img width="869" alt="capture d ecran 2017-05-12 a 21 56 48" src="https://cloud.githubusercontent.com/assets/24650759/26014971/329ac17e-375f-11e7-9523-8e573f4a04d7.png">

**Comment by thibaultvanc** [comment]
1 - supprimer toute la ligne "thank you for your registration..."
**FAIT**

2 - la phrase "I declare..." déborde du cadre
**FAIT**

3 - la case ne doit pas être par défaut cochée
**OK** C'est le cas il ne faut juste pas que le commercial lui pre-coche..

4 - "link to Terms and Conditions" doit être au dessus de "I declare..." et doit ouvrir les CGV dans une nouvelle fenêtre et non pas dans la même.
**FAIT**

5 - le clic sur "previous" m'a ramené à la phase 1 du process d'inscription
**FAIT**

**Comment by Playologie** [comment]
point 3 - dans le cas présent (no Smoking) la case est cochée par défaut. Est-ce donc parce qu'elle a été cochée dans le backoffice? Si oui, vous pouvez clôturer le ticket.

**Comment by thibaultvanc** [comment]
oui, c'est le cas, je close
