### ISSUE TITLE
écran "Thank you 2"

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#76]
1 - les br sont visibles
2 - on répète deux fois la même chose
3 - le https://www.playologie.com : afficher de la même manière que le lien vers les terms and conditions
<img width="820" alt="capture d ecran 2017-05-12 a 22 14 19" src="https://cloud.githubusercontent.com/assets/24650759/26015228/6c16cb54-3760-11e7-8481-826c85f45dc5.png">

**Comment by thibaultvanc** [comment]
1 - les br sont visibles 
**FAIT**

2 - on répète deux fois la même chose
**FAIT**

3 - le https://www.playologie.com : afficher de la même manière que le lien vers les terms and conditions
**FAIT**
