### ISSUE TITLE
problèmes graphiques

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#77]
1 - sur un petit écran, toute la partie de droite disparaît.

<img width="945" alt="capture d ecran 2017-05-13 a 15 30 41" src="https://cloud.githubusercontent.com/assets/24650759/26025985/16fbd4d2-37f3-11e7-85a3-07d9b1627c54.png">

2 - supprimer partout les "proudly larastraped..."

**Comment by thibaultvanc** [comment]
1 - sur un petit écran, toute la partie de droite disparaît.
**FAIT**

2 - supprimer partout les "proudly larastraped..."
**FAIT**

**Comment by Playologie** [comment]
- point 1 : ok mais laisser une petite marge à droite.

![marge](https://cloud.githubusercontent.com/assets/24650759/26051678/2cb839ca-3963-11e7-9b9a-cd29a3483d05.jpg)
