### ISSUE TITLE
Les couleurs passent bien mais pas les imprimés. 

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/playologie_exports#8]
"
Exemple 
Marque mfb@playologie.com / man2017
Commande :
http://playologie.com/brand-order/#/order/3382
"

**Comment by Playologie** [comment]
Elargir la zone pour faire un rectangle 
![capture d ecran 2017-02-02 a 15 02 13](https://cloud.githubusercontent.com/assets/24650759/22552297/9ca71ed2-e958-11e6-93f4-e8e2a9bf49bd.png)

**Comment by thibaultvanc** [comment]
ceci est fait
