### ISSUE TITLE
"back" manquant

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#80]
1 - bouton back manquant (à mettre juste au-dessus du nom de la marque)
2 - masquer le "new table"

<img width="859" alt="capture d ecran 2017-05-13 a 16 32 33" src="https://cloud.githubusercontent.com/assets/24650759/26026363/e221a06e-37f9-11e7-80a5-f2df9469a698.png">

**Comment by thibaultvanc** [comment]
fait
