### ISSUE TITLE
contact detail

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#84]
voici une première maquette que nous devons affiner à deux car je ne comprends pas les infos qui sont dessus.
maquette OK en tous cas pour tout ce qui concerne la partie supérieure aux onglets

![fiche_contact_details](https://cloud.githubusercontent.com/assets/24650759/26029177/3c02ecb6-382f-11e7-9a42-6dde8c232cfa.jpg)

**Comment by thibaultvanc** [comment]
ok maquette reproduite
J'en ai profité pour mettre en place le formulaire pour updater un contact

**Comment by Playologie** [comment]
il vaut mieux que l'on update en direct au téléphone, difficile d'expliquer et j'ai besoin que vous m'expliquiez 2 ou 3 trucs
