### ISSUE TITLE
contact_Plans

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#86]
merci de reproduire la maquette

![fiche_contact_plans](https://cloud.githubusercontent.com/assets/24650759/26029191/b4236c0c-382f-11e7-8a40-f46d03821dee.jpg)

**Comment by Playologie** [comment]
plusieurs petites modifs non prises en compte:

![tax](https://cloud.githubusercontent.com/assets/24650759/26052493/f6f89e58-3965-11e7-8150-c08077213736.jpg)

**Comment by thibaultvanc** [comment]
**OK fait,**
Par ailleurs, j'ai passé les 2 dernieres lignes en noire. Cela me paraissait plus lisible. N'hesitez pas à me dire ce que vous préférez

**Comment by Playologie** [comment]
dernière ligne en rouge, les précédentes en noir

**Comment by thibaultvanc** [comment]
FAIT - pas encore en ligne

**Comment by thibaultvanc** [comment]
en ligne
