### ISSUE TITLE
contact_subscription

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#87]
merci de reproduire les 2 maquette suivantes. Pour la 2eme maquette, j'ai laissé l'icône poubelle pourtant sans comprendre ce qu'elle fait.

![fiche_contact_subscription](https://cloud.githubusercontent.com/assets/24650759/26029198/f6723f8e-382f-11e7-8321-117190c4f3ef.jpg)

![fiche_contact_subscription 2](https://cloud.githubusercontent.com/assets/24650759/26029200/fac03a6e-382f-11e7-9f02-f600fff4c840.jpg)

**Comment by thibaultvanc** [comment]
**Fait**
-
effectivement, pour le screen 2, pas besoin de btn-delete

**Comment by Playologie** [comment]
- manque le "back" au dessus du nom de la société
- message to the Playologie team: les retour à la ligne saisi dans le formulaire d'inscription n'est pas pris en compte ici
- justifier à gauche le "edit on Zoho" et resserrer les lignes de la partie supérieure
- supprimer le "fake it" dans le mode édition
- tout les textes sont un peu décalés par rapport aux titres (ils sont un peu plus haut)

**Comment by thibaultvanc** [comment]
manque le "back" au dessus du nom de la société
**FAIT**

message to the Playologie team: les retour à la ligne saisi dans le formulaire d'inscription n'est pas pris en compte ici
**FAIT**

justifier à gauche le "edit on Zoho" et resserrer les lignes de la partie supérieure
**FAIT**

supprimer le "fake it" dans le mode édition
**FAIT**

tout les textes sont un peu décalés par rapport aux titres (ils sont un peu plus haut)
**FAIT**
