### ISSUE TITLE
pourcentage de remise dans subscription

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#93]
il faut pouvoir utiliser des fractions, actuellement ça arrondit automatiquement.

**Comment by thibaultvanc** [comment]
vous vouvez dire des discount du type 10,5 %
?

**Comment by thibaultvanc** [comment]
fait

**Comment by thibaultvanc** [comment]
ATTENTION DANS PLAN SUBSCRIPTION

**Comment by thibaultvanc** [comment]
fait
