### ISSUE TITLE
calcul de la TVA

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#94]
attention la TVA se calcule sur le montant HT non remisé

<img width="806" alt="capture d ecran 2017-05-15 a 20 55 04" src="https://cloud.githubusercontent.com/assets/24650759/26074080/dbe00994-39b0-11e7-9293-5138ae555f69.png">

**Comment by thibaultvanc** [comment]
fait

**Comment by Playologie** [comment]
non toujours pas et m calcule avec le mauvais taux de maintenant c'est encore pire parce que le total TTC se calcule avec le mauvais taux de TVA

<img width="624" alt="capture d ecran 2017-05-16 a 21 10 03" src="https://cloud.githubusercontent.com/assets/24650759/26123706/21b6801c-3a7c-11e7-97d1-85e096cb9b1c.png">

**Comment by thibaultvanc** [comment]
ok fait
