### ISSUE TITLE
ajout pays

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#96]
quand on s'inscrit en tant que marque il ne faut pas mettre de pays pour la marque à l'écran "select brand", mais le problème est qu'on ne peut avancer plus loin, le pays est requis pour aller à l'étape suivante!

<img width="950" alt="capture d ecran 2017-05-15 a 21 09 51" src="https://cloud.githubusercontent.com/assets/24650759/26074697/197b372c-39b3-11e7-887e-10032390eb8a.png">

**Comment by thibaultvanc** [comment]
fait - pas encore en ligne
