### ISSUE TITLE
clé billingMethodSelected

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/playologie_exports#99]
je ne trouve pas cette clé dans le fichiers de trad et en plus (si c'est bien la clé que je crois que c'est!) elle devrait se placer juste en dessous de 'Bank wire" lorsqu'il est coché.
Si vous trouvez la clé ou si vous l'ajoutez, merci de mettre "An invoice with our full bank details will be sent to you shortly."

![billing](https://cloud.githubusercontent.com/assets/24650759/26129894/92074cd2-3a92-11e7-83a1-781c3273bce7.jpg)

**Comment by thibaultvanc** [comment]
la clef est fans le fichier Web.php (ligne) 
billing > transfer > description

**Comment by thibaultvanc** [comment]
fait - en attente de la traduction
